//* This environment file has being generated by set-apiRoute.sh script at:  Thu Mar 9 10:14:32 CET 2023

var apiRoute:string = '';
      export const environment = {
        production: false,
        backendURL:  apiRoute,
        userListURL: apiRoute + '/api/person/all',
        userAddURL:  apiRoute + '/api/person/add'
      };
